version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: dependa
  reviewers:
  - JhonM
  ignore:
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.14
    - 7.13.15
  - dependency-name: rollup
    versions:
    - 2.44.0
    - 2.45.1
  - dependency-name: "@semantic-release/npm"
    versions:
    - 7.1.0
  commit-message:
    prefix: fix
